wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.3
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710802174.0
    t:
      1:
      - 1
      - 5
      - 41
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.7.3
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
exp:
  desc: null
  value:
    name: exp03-frac100
data_loader:
  desc: null
  value:
    import: src.data_loader.dataset.MultiCohortDataset
    batch_size:
      train: 256
      eval: 256
      test: 256
    data:
      train:
      - - isruc
        - train
      - - mros
        - train
      - - shhs
        - train
      - - ssc
        - train
      - - wsc
        - train
      eval:
      - - isruc
        - eval
      - - mros
        - eval
      - - shhs
        - eval
      - - ssc
        - eval
      - - wsc
        - eval
      test:
      - - isruc
        - test
      - - mros
        - test
      - - shhs
        - test
      - - ssc
        - test
      - - wsc
        - test
    data_dir: ./data/processed_oak
    modalities:
    - eeg
    - eog
    - emg
    train_fraction: null
    num_classes: 5
    segment_length: 300
network:
  desc: null
  value:
    import: src.model.rnn_model.RnnModel
    filter_base: 4
    kernel_size: 3
    max_pooling: 2
    num_blocks: 7
    rnn_bidirectional: true
    rnn_num_layers: 1
    rnn_num_units: 1024
loss:
  desc: null
  value:
    import: src.model.losses.temporal_crossentropy_loss
metrics:
  desc: null
  value:
  - overall_accuracy
  - balanced_accuracy
  - kappa
optimizer:
  desc: null
  value:
    import: torch.optim.SGD
    args:
      lr: 0.1
      momentum: 0.9
      nesterov: true
lr_scheduler:
  desc: null
  value:
    import: torch.optim.lr_scheduler.CyclicLR
    args:
      base_lr: 0.05
      max_lr: 0.15
      step_size_up: 500
      mode: triangular
trainer:
  desc: null
  value:
    epochs: 40
    log_dir: experiments/runs
    monitor: min val_loss
    n_gpu: 4
    num_workers: 128
    save_dir: experiments
    save_freq: 1
    tensorboardX: false
    verbosity: 2
