wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.3
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710893811.0
    t:
      1:
      - 1
      - 5
      - 41
      - 55
      3:
      - 23
      4: 3.7.3
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
